---
- name: Testing andrewrothstein.reloader
  hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Executing 'Reloader --version'
      ansible.builtin.command: /usr/local/bin/Reloader --version
      changed_when: false
      register: reloader_test_output
    - name: Output from 'Reloader --version'
      ansible.builtin.debug:
        msg: '{{ reloader_test_output.stdout }}'
