---
- hosts: all
  roles:
  - role: '{{ playbook_dir }}'
  tasks:
    - command: /usr/local/bin/Reloader --version
      register: reloader_test_output
    - name: Reloader --version
      debug:
        msg: '{{ reloader_test_output.stdout }}'
