---
- name: Installing andrewrothstein.unarchivedeps
  ansible.builtin.include_role:
    name: andrewrothstein.unarchivedeps
- name: Resolve platform specific vars
  ansible.builtin.include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: Check for install at {{ reloader_install_exe }}
  become: true
  ansible.builtin.stat:
    path: '{{ reloader_install_exe }}'
  register: reloader_binary
- name: Downloading and installing reloader
  when: not reloader_binary.stat.exists
  block:
    - name: Downloading {{ reloader_url }} to {{ reloader_tmp_tgz }}
      become: true
      become_user: root
      ansible.builtin.get_url:
        url: '{{ reloader_url }}'
        dest: '{{ reloader_tmp_tgz }}'
        checksum: '{{ reloader_checksum }}'
        mode: '644'
    - name: Mkdir -p {{ reloader_install_dir }}
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ reloader_install_dir }}'
        state: directory
        mode: '755'
    - name: Unarchiving {{ reloader_tmp_tgz }} to {{ reloader_install_dir }}
      become: true
      become_user: root
      ansible.builtin.unarchive:
        remote_src: true
        src: '{{ reloader_tmp_tgz }}'
        dest: '{{ reloader_install_dir }}'
        creates: '{{ reloader_install_exe }}'
  always:
    - name: Rm -f {{ reloader_tmp_tgz }}
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ reloader_tmp_tgz }}'
        state: absent
- name: Linking {{ reloader_link }} to {{ reloader_install_exe }}
  become: true
  become_user: root
  ansible.builtin.file:
    src: '{{ reloader_install_exe }}'
    dest: '{{ reloader_link }}'
    state: link
